# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/onlineexam?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
server.port=6900

# pCloud API Configuration
pcloud.username=kksathish577@gmail.com
pcloud.password=Sathishkumar12!

pcloud.api.upload-url=http://localhost:6900/api/files/upload
